### ISSUE TITLE
Node ID change

### ISSUE THREAD

**Issue by bsimmo** [ConnectedHumber/monitAir#4]
@BNNorman / @robinharris 
CHASR-6f3bd82c-1 is replacing
CHASR-ea086b27-1

direct replacement.  Should be live by 2019-03-31T20:00+01:00 ;-)

CHASR-ea086b27-1 is offline so not sending in any more data.

**Comment by BNNorman** [comment]
I guess you need historic data for the olde devices removing.

**Comment by BNNorman** [comment]
Oh, and is the device type the same?

**Comment by BNNorman** [comment]
The new device has been added so data will be collected when it starts sending..

**Comment by bsimmo** [comment]
*CHASR-6f3bd82c-1 is replacing
CHASR-ea086b27-1

direct replacement
*
